### ISSUE TITLE
BUG: final column missing

### ISSUE THREAD

**Issue by Segelzwerg** [Segelzwerg/Rechnung#262]
![image](https://github.com/user-attachments/assets/da29ec72-5fe0-497e-9403-37d597a252b6)

```
Traceback (most recent call last):
  File "/home/marcel/.cache/pypoetry/virtualenvs/rechnung-6JpnXrIb-py3.13/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcel/.cache/pypoetry/virtualenvs/rechnung-6JpnXrIb-py3.13/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

The above exception (no such column: invoice_invoice.final) was the direct cause of the following exception:
  File "/home/marcel/.cache/pypoetry/virtualenvs/rechnung-6JpnXrIb-py3.13/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcel/.cache/pypoetry/virtualenvs/rechnung-6JpnXrIb-py3.13/lib/python3.13/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/marcel/.cache/pypoetry/virtualenvs/rechnung-6JpnXrIb-py3.13/lib/python3.13/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcel/.cache/pypoetry/virtualenvs/rechnung-6JpnXrIb-py3.13/lib/python3.13/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcel/.cache/pypoetry/virtualenvs/rechnung-6JpnXrIb-py3.13/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcel/.cache/pypoetry/virtualenvs/rechnung-6JpnXrIb-py3.13/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcel/.cache/pypoetry/virtualenvs/rechnung-6JpnXrIb-py3.13/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcel/.cache/pypoetry/virtualenvs/rechnung-6JpnXrIb-py3.13/lib/python3.13/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcel/.cache/pypoetry/virtualenvs/rechnung-6JpnXrIb-py3.13/lib/python3.13/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/marcel/.cache/pypoetry/virtualenvs/rechnung-6JpnXrIb-py3.13/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcel/.cache/pypoetry/virtualenvs/rechnung-6JpnXrIb-py3.13/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcel/.cache/pypoetry/virtualenvs/rechnung-6JpnXrIb-py3.13/lib/python3.13/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcel/.cache/pypoetry/virtualenvs/rechnung-6JpnXrIb-py3.13/lib/python3.13/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/marcel/.cache/pypoetry/virtualenvs/rechnung-6JpnXrIb-py3.13/lib/python3.13/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcel/.cache/pypoetry/virtualenvs/rechnung-6JpnXrIb-py3.13/lib/python3.13/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcel/.cache/pypoetry/virtualenvs/rechnung-6JpnXrIb-py3.13/lib/python3.13/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/marcel/.cache/pypoetry/virtualenvs/rechnung-6JpnXrIb-py3.13/lib/python3.13/site-packages/django/template/defaulttags.py", line 199, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "/home/marcel/.cache/pypoetry/virtualenvs/rechnung-6JpnXrIb-py3.13/lib/python3.13/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
    ^^^^^^^^^^^^^^^^^
  File "/home/marcel/.cache/pypoetry/virtualenvs/rechnung-6JpnXrIb-py3.13/lib/python3.13/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcel/.cache/pypoetry/virtualenvs/rechnung-6JpnXrIb-py3.13/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              
  File "/home/marcel/.cache/pypoetry/virtualenvs/rechnung-6JpnXrIb-py3.13/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcel/.cache/pypoetry/virtualenvs/rechnung-6JpnXrIb-py3.13/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcel/.cache/pypoetry/virtualenvs/rechnung-6JpnXrIb-py3.13/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           
  File "/home/marcel/.cache/pypoetry/virtualenvs/rechnung-6JpnXrIb-py3.13/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcel/.cache/pypoetry/virtualenvs/rechnung-6JpnXrIb-py3.13/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcel/.cache/pypoetry/virtualenvs/rechnung-6JpnXrIb-py3.13/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcel/.cache/pypoetry/virtualenvs/rechnung-6JpnXrIb-py3.13/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcel/.cache/pypoetry/virtualenvs/rechnung-6JpnXrIb-py3.13/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Exception Type: OperationalError at /invoices/
Exception Value: no such column: invoice_invoice.final
```

**Comment by Segelzwerg** [comment]
This seems to be a problem with migrations not being applied correctly after merging them and having previously some of them applied.

**Comment by Segelzwerg** [comment]
Fixed by rolling back to 0029, manually adding a column `final` in the `invoice_invoice` with `Not Null` and default `FALSE` and then migrating all over migrations.
