### ISSUE TITLE
BUG: total is inprecise

### ISSUE THREAD

**Issue by Segelzwerg** [Segelzwerg/Rechnung#87]
```
FAIL: test_invoice_total (invoice.tests.InvoiceModelTestCase.test_invoice_total)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/Rechnung/Rechnung/invoice/tests.py", line 273, in test_invoice_total
    self.assertEqual(invoice.total, first_item.total + second_item.total)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Decimal('4586577[35](https://github.com/Segelzwerg/Rechnung/actions/runs/11970717459/job/33374044339#step:8:36)976522242612.6907') != Decimal('458657735976521807665.7937')
```

**Comment by Segelzwerg** [comment]
Net total also affected
```
======================================================================
FAIL: test_invoice_net_total (invoice.tests.InvoiceModelTestCase.test_invoice_net_total)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/Rechnung/Rechnung/invoice/tests.py", line 264, in test_invoice_net_total
    self.assertEqual(invoice.net_total, first_item.net_total + second_item.net_total)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Decimal('-69996940[32](https://github.com/Segelzwerg/Rechnung/actions/runs/11970923176/job/33374658112?pr=84#step:8:33)39763077.45') != Decimal('-699969403239763551.25')

----------------------------------------------------------------------
```
